spring :
  datasource :
    url : jdbc:mysql://localhost:3306/student
    username : root
    password : Rashen1234

  jpa :
    hibernate :
      ddl-auto : update

      spring:
        datasource:
